version: '3.3'
services:
  SPEC:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '5005:3306'
    volumes:
      - my-db:/var/lib         /mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '5050:8080'
volumes:
  my-db: